# Generated by Django 5.2.3 on 2025-06-12 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название бейджа')),
                ('description', models.TextField(verbose_name='Описание (за что дается)')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код бейджа')),
                ('image_url', models.URLField(max_length=255, verbose_name='URL иконки бейджа')),
            ],
            options={
                'verbose_name': 'Бейдж',
                'verbose_name_plural': 'Бейджи',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL обложки')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения')),
            ],
            options={
                'verbose_name': 'Прогресс пользователя',
                'verbose_name_plural': 'Прогрессы пользователей',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название навыка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='courses.course', verbose_name='Курс')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.skill', verbose_name='Родительский навык')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('theory_content', models.JSONField(default=list, verbose_name='Содержимое теории (JSON)')),
                ('xp_reward', models.PositiveIntegerField(default=10, verbose_name='Награда в XP')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['skill', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('multiple_choice', 'Множественный выбор'), ('true_false', 'Верно/Неверно'), ('text_input', 'Ввод текста'), ('code', 'Кодовая задача')], max_length=20, verbose_name='Тип задания')),
                ('question', models.TextField(verbose_name='Текст вопроса')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='Варианты ответа (JSON)')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Правильный ответ')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст подсказки')),
                ('xp_penalty', models.PositiveIntegerField(default=1, verbose_name='Штраф в XP за использование')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='courses.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Подсказка',
                'verbose_name_plural': 'Подсказки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.badge', verbose_name='Бейдж')),
            ],
            options={
                'verbose_name': 'Бейдж пользователя',
                'verbose_name_plural': 'Бейджи пользователей',
            },
        ),
    ]
