# Generated by Django 5.2.3 on 2025-06-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='code_template',
            field=models.TextField(blank=True, null=True, verbose_name='Шаблон кода'),
        ),
        migrations.AlterField(
            model_name='task',
            name='options',
            field=models.JSONField(blank=True, null=True, verbose_name='Опции/Блоки (JSON)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('multiple_choice', 'Множественный выбор'), ('true_false', 'Верно/Неверно'), ('text_input', 'Ввод текста'), ('code', 'Кодовая задача'), ('fill_in_blank', 'Вставить пропущенное'), ('constructor', 'Конструктор кода')], max_length=20, verbose_name='Тип задания'),
        ),
    ]
