# Generated by Django 5.2.3 on 2025-06-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_task_code_template_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('multiple_choice', 'Множественный выбор'), ('true_false', 'Верно/Неверно'), ('text_input', 'Ввод текста'), ('code', 'Кодовая задача'), ('fill_in_blank', 'Вставить пропущенное'), ('constructor', 'Конструктор кода'), ('speed_typing', 'Печать на скорость')], max_length=20, verbose_name='Тип задания'),
        ),
    ]
