# Generated by Django 5.2.3 on 2025-06-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, help_text="Используется для заданий 'Печать на скорость'.", null=True, verbose_name='Лимит времени (в секундах)'),
        ),
    ]
