# Generated by Django 5.2.3 on 2025-06-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_task_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='correct_answer',
            field=models.TextField(verbose_name='Правильный ответ'),
        ),
    ]
