# Generated by Django 5.2.3 on 2025-08-30 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0007_challenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('number_of_questions', models.PositiveIntegerField(default=100)),
                ('passing_score', models.PositiveIntegerField(default=80, help_text='Проходной балл в процентах')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certification_test', to='courses.course')),
            ],
            options={
                'verbose_name': 'Сертификационный тест',
                'verbose_name_plural': 'Сертификационные тесты',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('multiple_choice', 'Множественный выбор'), ('true_false', 'Верно/Неверно'), ('text_input', 'Ввод текста'), ('code', 'Кодовая задача'), ('fill_in_blank', 'Вставить пропущенное')], max_length=20)),
                ('question', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.TextField()),
                ('code_template', models.TextField(blank=True, null=True)),
                ('difficulty', models.PositiveIntegerField(default=1, help_text='Сложность от 1 (легкий) до 5 (сложный)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='courses.course')),
            ],
            options={
                'verbose_name': 'Вопрос из банка',
                'verbose_name_plural': 'Банк вопросов',
            },
        ),
        migrations.CreateModel(
            name='UserTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, help_text='Итоговый балл в процентах', null=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('session_data', models.JSONField(default=dict)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.certificationtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Попытка теста',
                'verbose_name_plural': 'Попытки тестов',
            },
        ),
    ]
